export const CRUD_GET_LIST_START = "CRUD_GET_LIST_START"
export const CRUD_UPDATE_START = "CRUD_UPDATE_START"
export const CRUD_GET_LIST_OK = "CRUD_GET_LIST_OK"
export const CRUD_UPDATE_OK = "CUD_UPDATE_OK"